/*
 * ultrasonic.c
 *
 *  Created on: Oct 2, 2025
 *  Author: Kerolous-Labib
 */

#include"ultrasonic.h"


uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;

/* Create configuration structure for ICU driver */
ICU_ConfigType ICU_Configurations = {
		.clock = F_CPU_8,
		.edge = RAISING
};

/*
 * Description:
 * 	1. Initialize the ICU driver as required.
 * 	2. Set up the ICU callback function.
 * 	3. Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/* Set the direction for the trigger pin as output through the GPIO driver. */
	GPIO_setupPinDirection(TRIGGER_PORT,TRIGGER_PIN,PIN_OUTPUT);
	/* Initialize the ICU driver as required. */
	ICU_init(&ICU_Configurations);
	/* Set the Call back function pointer in the ICU driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);
}


/* Description:
 * 	Send the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN,LOGIC_HIGH);
	_delay_us(20);
	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN,LOGIC_LOW);
}

/*
 * Description:
 * 	1. Send the trigger pulse by using the Ultrasonic_Trigger function.
 * 	2. Start the measurement process via the ICU driver.
 *
 * 	Return: The measured distance in centimeters.
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance;
	float  period = 0;
	/* Send the trigger pulse by using the Ultrasonic_Trigger function. */
	Ultrasonic_Trigger();

	if(g_edgeCount == 1){

		g_edgeCount = 0;
		/* calculate the period */
		period = g_timeHigh * TIMER_TICK_TIME_SEC;
		/* calculate the distance */
		distance = (uint16)((period * SOUND_SPEED) / 2);
	}

	return distance;
}


/* Description:
 * 	1. This is the callback function called by the ICU driver.
 * 	2. It calculates the high time (pulse time) generated by the ultrasonic sensor.
 */

/* This is the call-back function */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		g_timeHigh = ICU_getInputCaptureValue();
		//ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();
		/* Detect rising edge */

		ICU_setEdgeDetectionType(RAISING);

	}
}
