/*
 * ultrasonic.h
 *
 *  Created on: Oct 2, 2025
 *      Author: Kerolous-Labib
 */

#ifndef SRC_ULTRASONIC_H_
#define SRC_ULTRASONIC_H_

/*******************************************************************************
 *                                Libraries                                    *
 *******************************************************************************/
#include <avr/io.h>
#include <util/delay.h>
#include "gpio.h"
#include "icu.h"
/*******************************************************************************
 *                               Global Variables                              *
 *******************************************************************************/


/* Create configuration structure for ICU driver */
ICU_ConfigType ICU_Configurations;


/*******************************************************************************
 *                                 Definitions                                 *
 *******************************************************************************/
#define TRIGGER_PORT                 PORTD_ID
#define TRIGGER_PIN                  PIN7
#define ECHO_PORT                    PORTD_ID
#define ECHO_PIN                     PIN6

#define SOUND_SPEED                  34000        /* speed of sound in cm/s */
#define TIMER_TICK_TIME_SEC          (1e-6)    /* 1 µs per tick at F_CPU = 8MHz, prescaler = 8 */

/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/


/*
 * Description:
 * 	1. Initialize the ICU driver as required.
 * 	2. Set up the ICU callback function.
 * 	3. Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void);


/* Description:
 * 	Send the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description:
 * 	1. Send the trigger pulse by using the Ultrasonic_Trigger function.
 * 	2. Start the measurement process via the ICU driver.
 *
 * 	Return: The measured distance in centimeters.
 */
uint16 Ultrasonic_readDistance(void);


/* Description:
 * 	1. This is the callback function called by the ICU driver.
 * 	2. It calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


#endif /* SRC_ULTRASONIC_H_ */
